"""add user table with check constraint

Revision ID: 6977927c39de
Revises: 0c1a5207d3d1
Create Date: 2026-06-01 15:43:45.539036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6977927c39de'
down_revision: Union[str, Sequence[str], None] = '0c1a5207d3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('works_in_shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'shops', ['works_in_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'works_in_shop_id')
    # ### end Alembic commands ###
